version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - node --version
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g typescript
  build:
    on-failure: ABORT
    commands:
      - echo Build started on $(date '+%Y-%m-%d %H:%M:%S %Z')
      # - export NODE_OPTIONS="--max-old-space-size=2048"
      - npm run build-prod
      - rm -rf build/* && tsc -b ./tsconfig.json
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on $(date '+%Y-%m-%d %H:%M:%S %Z')
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
